# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: partsunlimited007

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '2.2'               # set this to the .NET Core version to use

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - '.github/**'      
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest #ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build PartsUnlimited.sln --configuration Release
        
#      - name: Install Node
#        uses: actions/setup-node@v3
#        with:
#          node-version: 14

#      - name: Build SASS
#        run: |
#          cd src/PartsUnlimitedWebsite/
#          npm install --python=python2.7
#          npm config set python python2.7
#          npm install grunt-cli
#          grunt
                    
      - name: dotnet publish
        run: dotnet publish PartsUnlimited.sln -c Release -o ./published

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ./published

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'partsunlimited007'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C0EC1D11A2B341A68F6B939D73363623 }}
          package: .
